# Generated by Django 5.2.7 on 2025-11-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название заболевания')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Кожное заболевание',
                'verbose_name_plural': 'Справочник кожных заболеваний',
            },
        ),
    ]
