# Generated by Django 5.2.7 on 2025-11-05 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_diagnosisrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Уверенность')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='core.skincondition', verbose_name='Определённое заболевание')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.diagnosisrequest', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Результат диагностики',
                'verbose_name_plural': 'Результаты диагностики',
            },
        ),
    ]
