# Generated by Django 5.2.7 on 2025-11-05 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_diagnosisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='core.skincondition', verbose_name='Фактическое заболевание')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'dermatologist'}, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL, verbose_name='Врач-дерматолог')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='core.diagnosisresult', verbose_name='Результат диагностики')),
            ],
            options={
                'verbose_name': 'Медицинская верификация',
                'verbose_name_plural': 'Медицинские верификации',
            },
        ),
    ]
