# Generated by Django 5.2.7 on 2025-11-29 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_medicalverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrequest',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_diagnosis_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ответсвенный дерматолог'),
        ),
        migrations.AddField(
            model_name='skincondition',
            name='description',
            field=models.TextField(blank=True, default='Ничего нет', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Пациент'), ('dermatologist', 'Дерматолог'), ('admin', 'Администратор')], default='patient', max_length=20, verbose_name='роль'),
        ),
    ]
