# Generated by Django 5.2.7 on 2025-12-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_diagnosisrequest_responsible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisrequest',
            name='responsible',
        ),
    ]
